config/routes.rb
Cardslap::Application.routes.draw do
  root :to => 'home#index'

  resources :decks do
    resources :cards
    resources :shares, :only => [:new, :create, :destroy, :show]
    resources :quiz, :only => [:index]
  end

  resources :passwords,
    :controller => 'clearance/passwords',
    :only       => [:new, :create]

  resource  :session,
    :controller => 'clearance/sessions',
    :only       => [:create, :destroy]

  resources :users, :controller => 'clearance/users' do
    resource :password,
      :controller => 'clearance/passwords',
      :only       => [:create, :edit, :update]
  end

  match 'sign_up'  => 'clearance/users#new', :as => 'sign_up'
  match 'sign_in'  => 'clearance/sessions#new', :as => 'sign_in'
  match 'sign_out' => 'clearance/sessions#destroy', :via => :delete, :as => 'sign_out'
  match 'account'  => 'clearance/users#edit'
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :decks
end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < ApplicationController
  unloadable

  before_filter :authorize
  skip_before_filter :authorize,   :only => [:new, :create]
  before_filter :redirect_to_root, :only => [:new, :create], :if => :signed_in?

  def new
    @user = Clearance.configuration.user_model.new(params[:user])
    render :template => 'users/new', :layout => 'marketing'
  end

  def edit
    @user = current_user
    render :template => 'users/show'
  end

  def update
    @user = current_user
    if @user.update_password(params[:user][:password])
      redirect_to account_path
      flash[:notice] = 'Password updated'
    else
      redirect_to account_path
      flash[:notice] = "Password can't be blank"
    end
  end

  def create
    @user = Clearance.configuration.user_model.new(params[:user])
    if @user.save
      sign_in(@user)
      redirect_back_or root_url
    else
      flash_failure_after_create
      render :template => 'users/new', :layout => 'marketing'
    end
  end

  private

  def flash_failure_after_create
    flash.now[:notice] = translate(:bad_email_or_password,
      :scope   => [:clearance, :controllers, :passwords],
      :default => "That account may already exist.")
  end
end

app/views/users/new.html.erb
<div class="cards">
  <% 30.times do %>
    <div class="card">
      <div class="front"></div>
      <div class="back"></div>
    </div>
  <% end %>
</div>

<h1 class="logo"><span>Card</span><span>slap</span></h1>

<section class="pitch">
  <p>CardSlap is a website for making flashcards. You can put images or text on either side of a flashcard, you can sort them into decks, and you can mark them as memorized. If you need to resize them, you can do that too.</p>
  <p>Check out these examples on your computer or your phone:</p>
  <ul>
    <li><%= link_to 'An art history deck', 'arth-demo'%></li>
    <li><%= link_to 'A French vocab deck', 'french-demo'%></li>
  </ul>
</section>

<section class="auth">
  <section class="form sign-up">
    <h2>Create a Cardslap account</h2>
    <%= form_for @user do |form| %>
      <%= form.text_field :email, :type => 'email', :placeholder => 'email', :value => params['email'] %>
      <%= form.password_field :password, :placeholder => 'password' %>
      <%= form.submit 'Create an account' %>
    <% end %>
  </section>
  <section class="form sign-in">
    <h2>Already have an account?</h2>
    <%= form_for :session, :url => session_path do |form| %>
      <%= form.text_field :email, :type => 'email', :placeholder => 'email' %>
      <%= form.password_field :password, :placeholder => 'password' %>
      <%= link_to "forgot?", new_password_path, :class => 'reset' %>
      <%= form.submit "Sign in" %>
    <% end %>
  </section>
</section>

app/views/users/show.html.erb
<aside class="update">
  <%= form_for @user, :html => { :class => 'update vertical' } do |form| %>
    <%= form.text_field :email, :type => 'email', :disabled => 'disabled' %>
    <%= form.password_field :password, :placeholder => 'new password' %>
    <%= form.submit "Update account" %>
  <% end %>
</aside>