config/routes.rb
Cardslap::Application.routes.draw do
  root :to => 'home#index'

  resources :decks do
    resources :cards
    resources :shares, :only => [:new, :create, :destroy, :show]
    resources :quiz, :only => [:index]
  end

  resources :passwords,
    :controller => 'clearance/passwords',
    :only       => [:new, :create]

  resource  :session,
    :controller => 'clearance/sessions',
    :only       => [:create, :destroy]

  resources :users, :controller => 'clearance/users' do
    resource :password,
      :controller => 'clearance/passwords',
      :only       => [:create, :edit, :update]
  end

  match 'sign_up'  => 'clearance/users#new', :as => 'sign_up'
  match 'sign_in'  => 'clearance/sessions#new', :as => 'sign_in'
  match 'sign_out' => 'clearance/sessions#destroy', :via => :delete, :as => 'sign_out'
  match 'account'  => 'clearance/users#edit'
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
  after_initialize :init

  def init
    self.sort_number ||= 0
  end

  comma do
    front
    back
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  helper :all
  before_filter :authorize

  def create
    @deck = current_user.decks.find(params[:deck_id])
    @card = @deck.cards.build(params[:card])
    @card.save
  end

  def destroy
    @deck = current_user.decks.find(params[:deck_id])
    @card = @deck.cards.find(params[:id])
    @card.destroy
  end

  def edit
    @deck = current_user.decks.find(params[:deck_id])
    @card = @deck.cards.find(params[:id])
  end

  def update
    @deck = current_user.decks.find(params[:deck_id])
    @card = @deck.cards.find(params[:id])

    # make sure the user isn't updating someone else's cards via a shared deck
    @shares = Share.find_all_by_email(current_user.email)
    shared_flag = false;
    @shares.each do |share|
      if share.deck_id == @deck.id
        shared_flag = true
      end
    end

    if shared_flag
      redirect_to @deck
    else
      @card.update_attributes(params[:card])
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  def is_string_image_extension? str
    return ['jpeg', 'jpg', 'png', 'gif', 'webp'].include? str.downcase
  end

  def is_string_image? str
    uri = URI.parse(str)
    # if string is a url and ends in an image extension, assume it's an image
    return %w(http https).include?(uri.scheme) &&
           is_string_image_extension?(uri.path.rpartition('.').last)

  # if URI.parse raises an invalid error, return false
  rescue URI::InvalidURIError
    return false
  end
end

app/views/cards/_card-form.html.erb
<%= form_for [deck, card], :html => { :class => 'card-form' }, :remote => true do |form| %>
  <div class="entries">
    <%= form.text_area :front, :placeholder => 'Front - to use an image, paste in the url' %>
    <%= form.text_area :back, :placeholder => 'Back - to use an image, paste in the url' %>
    <%= form.submit :value => 'save', :class => 'edit-card-button' %>
  </div>
<% end %>

app/views/cards/_card.html.erb
<li draggable="true" class="single-card" data-sort="<%= card.sort_number %>" data-id="<%= card.id %>" style="width: <%= card.width %>px; height: <%= card.height %>px;">
  <% if is_string_image?(card.front) %>
  <span class="front image">
    <img src="<%= card.front %>" />
  <% else %>
  <span class="front">
    <pre class="text"><%= card.front %></pre>
  <% end %>
    <div class="actions">
      <%= link_to edit_deck_card_path(deck, card), :remote => :true, :class => 'edit' do %>
        <i class="icon-pencil"></i>
      <% end %>
      <%= link_to [deck, card], :method => :delete, :remote => :true, :class => 'delete' do %>
        <i class="icon-remove"></i>
      <% end %>
    </div>
  </span>

  <% if is_string_image?(card.back) %>
    <span class="back image"><img src="<%= card.back %>" /></span>
  <% else %>
   <span class="back"><pre class="text"><%= card.back %></pre></span>
  <% end %>
</li>
<li class="reorder-target" style="height: <%= card.height %>px;"></li>

app/views/cards/_new-card-form.html.erb
<%= form_for [deck, card], :html => { :class => 'card-form' }, :remote => true do |form| %>
  <div class="entries">
    <%= form.hidden_field :front, :placeholder => 'Front - to use an image, paste in the url' %>
    <%= form.hidden_field :back, :placeholder => 'Back - to use an image, paste in the url' %>
  </div>
  <%= form.submit :value => 'New card', :class => 'new-card-button' %>
<% end %>

app/views/cards/create.js.erb
var html = "<%= escape_javascript(render(:partial => 'cards/card', :locals => { :deck => @deck, :card => @card })) %>";

$('#new_card').after(html);
$('#new_card textarea').val('');

// to make sure the new card is always the first in the deck, increase all other card sort numbers by one
<% @deck.cards.each do |card| %>
  <% if @card.id != card.id %>
    $.ajax({
      type: 'POST',
      url: '/decks/<%= @deck.id %>/cards/<%= card.id %>',
      data: {_method: 'PUT', card: {sort_number: <%= card.sort_number + 1 %>}}
    });
  <% end %>
<% end %>

// make new card auto editable
$('.single-card[data-id=<%= @card.id %>] a.edit').click();

app/views/cards/destroy.js.erb
if ($('.cards li[data-id=<%= @card.id %>]').length) {
  $('.cards li[data-id=<%= @card.id %>]').next('.reorder-target').remove();
}

$('#bin li[data-id=<%= @card.id %>], .cards li[data-id=<%= @card.id %>]').remove();

app/views/cards/edit.js.erb
var html = "<%= escape_javascript(render(:partial => 'cards/card-form', :locals => { :deck => @deck, :card => @card })) %>";

$('.single-card[data-id=<%= @card.id %>]').hide().after(html);

app/views/cards/update.js.erb
console.log('<%= @card.id %>');

$('#edit_card_<%= @card.id %>').remove();

if ('<%= params['card']['front'] %>') {
  $('.single-card[data-id=<%= @card.id %>] .front .text').text('<%= escape_javascript(params['card']['front']) %>');
  $('.single-card[data-id=<%= @card.id %>] .back .text').text('<%= escape_javascript(params['card']['back']) %>');
}

$('.single-card[data-id=<%= @card.id %>]').show().removeClass('flip');