config/routes.rb
Cardslap::Application.routes.draw do
  root :to => 'home#index'

  resources :decks do
    resources :cards
    resources :shares, :only => [:new, :create, :destroy, :show]
    resources :quiz, :only => [:index]
  end

  resources :passwords,
    :controller => 'clearance/passwords',
    :only       => [:new, :create]

  resource  :session,
    :controller => 'clearance/sessions',
    :only       => [:create, :destroy]

  resources :users, :controller => 'clearance/users' do
    resource :password,
      :controller => 'clearance/passwords',
      :only       => [:create, :edit, :update]
  end

  match 'sign_up'  => 'clearance/users#new', :as => 'sign_up'
  match 'sign_in'  => 'clearance/sessions#new', :as => 'sign_in'
  match 'sign_out' => 'clearance/sessions#destroy', :via => :delete, :as => 'sign_out'
  match 'account'  => 'clearance/users#edit'
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => {:scope => :user_id}
  has_many :cards, :dependent => :destroy, :order => 'sort_number'
  has_many :shares, :dependent => :destroy

  extend FriendlyId
  belongs_to :user
  friendly_id :name, :use => :scoped, :scope => :user

  def should_generate_new_friendly_id?
    new_record?
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :authorize

  def index
    @user = current_user

    @deck = Deck.new
    @decks = @user.decks

    @shares = Share.find_all_by_email(@user.email)
    @shared_decks = []
    @shares.each do |share|
      @shared_deck = Deck.find_by_id(share.deck_id)
      @shared_deck[:share_id] = share.id
      @shared_decks.push(@shared_deck);
    end
  end

  def create
    @user = current_user
    @deck = @user.decks.build(params[:deck])
    if (!@deck.invalid?(:name))
      @deck.save
      redirect_to deck_path(@deck)
    else
      redirect_to decks_path
      @deck.errors.messages.each do |msg|
        flash[:notice] = msg.last.last.capitalize
      end
    end
  end

  def show
    @user = current_user
    @deck = @user.decks.find(params[:id])
    @cards = @deck.cards
    @shares = @deck.shares

    @share = Share.new
    @card = Card.new

    respond_to do |format|
      format.html
      format.csv {
        render :csv => @cards, :filename => @deck.slug
      }
    end
  end

  def destroy
    @user = current_user
    @deck = @user.decks.find(params[:id])
    @deck.destroy
    redirect_to decks_path
  end

  def edit
    @user = current_user
    @deck = @user.decks.find(params[:id])
    @shares = @deck.shares
  end

  def update
    @user = current_user
    @deck = @user.decks.find(params[:id])

    if @deck.update_attributes(params[:deck])
      redirect_to decks_path
    else
      render :edit
    end
  end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_form.html.erb
<%= form_for @deck do |form| %>
  <%= form.text_area :name, placeholder: 'Click and enter a new deck name' %>
  <%= form.submit value: 'create deck' %>
<% end %>

app/views/decks/edit.html.erb
<%= form_for @deck do |form| %>
  <div class="textarea"><%= form.text_area :name %></div>
  <%= form.submit %>
<% end %>

app/views/decks/index.html.erb
<ul class="decks">
  <% @decks.each do |deck| %>
    <li class="deck">
      <%= link_to deck.name, deck %>
      <div class="actions">
        <%= link_to edit_deck_path(deck), :class => 'edit' do %>
          <i class="icon-pencil"></i>
        <% end %>
        <%= link_to deck, :method => :delete, :class => 'delete' do %>
          <i class="icon-remove"></i>
        <% end %>
      </div>
    </li>
  <% end %>
  <li class="create-deck">
    <%= render :partial => 'form', :locals => { :deck => @deck } %>
  </li>
  <% @shared_decks.each do |shared_deck| %>
    <li class="shared" data-shareid="<%= shared_deck.share_id %>">
      <%= link_to shared_deck.name, deck_share_path(shared_deck.id, shared_deck.share_id) %>
      <div class="actions">
        <%= link_to deck_share_path(shared_deck.id, shared_deck.share_id), :method => :delete, :remote => true, :class => 'delete' do %>
          <i class="icon-remove"></i>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/decks/show.html.erb
<ul class="cards" data-deck_id="<%= @deck.id %>">
  <%= render :partial => 'cards/new-card-form', :locals => { :deck => @deck, :card => @card } %>
  <% @cards.each do |card| %>
    <% if card.bin == 'main' %>
      <%= render :partial => 'cards/card', :locals => { :deck => @deck, :card => card } %>
    <% end %>
  <% end %>
  <li class="reorder-target last"></li>
  <li class="card-button"><%= link_to 'Enter quiz mode', deck_quiz_index_path(@deck), :class => "enter-quiz" %></li>
</ul>

<div id="bin">
  <h2>Memorized Pile</h2>
  <% @cards.each do |card| %>
    <% if card.bin == 'bin' %>
      <%= render :partial => 'cards/card', :locals => { :deck => @deck, :card => card } %>
    <% end %>
  <% end %>
</div>

<div class="exportshare">
  <a class="export" href="<%= request.url %>.csv"><i class="icon-download-alt"></i></a>
  <a class="share" href="#" data-toggle="dropdown"><i class="icon-share-alt"></i> share</a>
  <%= render :partial => 'shares/shares', :locals => { :deck => @deck, :share => @share } %>
</div>