config/routes.rb
Cardslap::Application.routes.draw do
  root :to => 'home#index'

  resources :decks do
    resources :cards
    resources :shares, :only => [:new, :create, :destroy, :show]
    resources :quiz, :only => [:index]
  end

  resources :passwords,
    :controller => 'clearance/passwords',
    :only       => [:new, :create]

  resource  :session,
    :controller => 'clearance/sessions',
    :only       => [:create, :destroy]

  resources :users, :controller => 'clearance/users' do
    resource :password,
      :controller => 'clearance/passwords',
      :only       => [:create, :edit, :update]
  end

  match 'sign_up'  => 'clearance/users#new', :as => 'sign_up'
  match 'sign_in'  => 'clearance/sessions#new', :as => 'sign_in'
  match 'sign_out' => 'clearance/sessions#destroy', :via => :delete, :as => 'sign_out'
  match 'account'  => 'clearance/users#edit'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cardslap</title>
  <%= stylesheet_link_tag "application" %>
  <script type="text/javascript" src="//use.typekit.net/jsr1pts.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1.0"/>
</head>
<body class="<% if flash[:notice] %>flash<% end %>">
  <div class="wrapper">
    <header>
      <h1>
        <a class="logo" href="<%= root_path %>">Cardslap</a>
        <span><%= header_deck_link %></span>
      </h1>
    </header>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
      <div class="clearfix"></div>
    <% end %>
    <% if signed_in? %>
      <%= yield %>
      <footer>
        <p><%= current_user.email %> <%= link_to 'sign out', sign_out_path, :method => :delete %>, <%= link_to 'account settings', account_path %></p>
      </footer>
    <% else %>
      <%= yield %>
    <% end %>
  </div>
</body>
</html>

app/views/layouts/marketing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cardslap, a flashcard app</title>
  <link href="http://fonts.googleapis.com/css?family=PT+Mono|Oswald" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1.0"/>
</head>
<body class="home <% if flash[:notice] %>flash<% end %>">
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
    <div class="clearfix"></div>
  <% end %>
  <%= yield %>
</body>
</html>